name: Build Release APK

on:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'gradle'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - uses: gradle/actions/setup-gradle@v3

    - run: gradle assembleGenericRelease



    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: signed-apks
        path: app/build/outputs/apk/generic/release/*.apk
        if-no-files-found: error
        retention-days: 20
