name: check 

on:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: check path 
      run: pwd

    - name: upload apk
      uses: actions/upload-artifact@v3
      with:
          name: build
          path: /home/runner/work/Seal/Seal/README.md
