name: Build test

on:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'gradle'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - uses: gradle/actions/setup-gradle@v3

    - run: gradle assembleGenericRelease


    - name: zip source and compiled apks
      run: 
         zip -r getit_build.zip

    - name: Upload the zipped files
      uses: actions/upload-artifact@v3
      with:
          name: build
          path: getit_build.zip

    - name: upload build file (just to test if it is uploading or not)
      uses: actions/upload-artifact@v3
      with:
          name: build
          path: app/build.gradle.kts
          
