name: Build test

on:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'gradle'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - uses: gradle/actions/setup-gradle@v3

    - run: gradle assembleGenericRelease

   
    - name: Zip the specific folder
      run:
          cd app/build
          zip -r build.zip .

    - name: Upload the zipped artifact
      uses: actions/upload-artifact@v3
        with:
          name: build
          path: app/build/build.zip

          
