name: Build test

on:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'gradle'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - uses: gradle/actions/setup-gradle@v3

    - run: gradle assembleGenericRelease

    - name: Find Latest APK
      run:
          apk_path=$(find . -name "*.apk" -type f -printf '%T+\t%p\n' | sort -r | head -n 1 | cut -f2-)
          echo "::set-path name=apk_path::$apk_path"
      id: find-apk
      
    - name: Upload APK Artifact
      uses: actions/upload-artifact@v3
      with:
          name: my-app
          path: ${{ steps.find-apk.outputs.apk_path }}
        
